FROM node:12.18.1
ENV NODE_ENV=production

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]